sudo: true
dist: trusty

language: node_js

node_js:
  - "4.0"
  - "4"
  - "5.0"
  - "5"
  - "6"

services:
  - postgresql

addons:
  - "9.6"

before_script:
  - set
  - psql -c "CREATE DATABASE test_db2;" -U postgres

script:
  - npm run test-pgsql

after_script:
  - npm run coveralls